name: Go

on: [pull_request, push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install dependencies
      run: sudo apt-get install libx11-dev

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
