name: Publish

on:
  push:
    branches:
      - 'testbuild'
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install dependencies
      run: sudo apt-get install xorg-dev

    - name: Prepare directories
      run: mkdir -p releases

    - name: Install Fyne bundler
      run: go get fyne.io/fyne/v2/cmd/fyne

    - name: Build Linux Package
      run: cd releases && fyne package -os linux -icon ../icon.png -sourceDir .. && cd ..

    - name: Release Linux Package
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: releases/impallette
        asset_name: impallette
        tag: ${{ github.ref }}

    - name: Build MacOS Package
      run: cd releases && fyne package -os darwin -icon ../icon.png -sourceDir .. && cd ..

    - name: Release MacOS Package
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: releases/impallette.app
        asset_name: impallette.app
        tag: ${{ github.ref }}

    # - name: Build Windows Package
    #  run: cd releases && fyne package -os windows -icon ../icon.png -sourceDir .. && cd ..

    # - name: Release Windows Package
    #   uses: svenstaro/upload-release-action@v2
    #   with:
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     file: releases/impallette.exe
    #     asset_name: impallette.exe
    #     tag: ${{ github.ref }}

