name: Publish

on:
  push:
    branches:
      - 'testbuild'
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install dependencies
      run: sudo apt-get install xorg-dev

    - name: Install Fyne bundler
      run: go get fyne.io/fyne/v2/cmd/fyne

    - name: Build Linux Package
      run: fyne package -os linux -icon icon.png

    # - name: Release Linux Package
    #   uses: svenstaro/upload-release-action@v2
    #   with:
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     file: impallette
    #     asset_name: impallette
    #     tag: ${{ github.ref }}

    - name: Build MacOS Package
      run: fyne package -os darwin -icon icon.png

    # - name: Release MacOS Package
    #   uses: svenstaro/upload-release-action@v2
    #   with:
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     file: impallette.app
    #     asset_name: impallette.app
    #     tag: ${{ github.ref }}

    # - name: Build Windows Package
    #   run: fyne package -os windows -icon icon.png

    # - name: Release Windows Package
    #   uses: svenstaro/upload-release-action@v2
    #   with:
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     file: impallette.exe
    #     asset_name: impallette.exe
    #     tag: ${{ github.ref }}

    - name: Release with assets
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'impallette;impallette.app;impallette.exe'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ github.ref }}
