name: Publish

on:
  push:
    branches:
      - 'testbuild'
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install dependencies
      run: sudo apt-get install xorg-dev

    - name: Install Fyne bundler
      run: go get fyne.io/fyne/v2/cmd/fyne

    - name: Build Linux Package
      run: fyne package -os linux -icon icon.png

    # - name: Release Linux Package
    #   uses: svenstaro/upload-release-action@v2
    #   with:
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     file: imgpalette
    #     asset_name: imgpalette
    #     tag: ${{ github.ref }}

    - name: Build MacOS Package
      run: fyne package -os darwin -icon icon.png
    - name: Zip MacOS Package
      run: zip -r imgpalette.zip imgpalette.app

    # - name: Release MacOS Package
    #   uses: svenstaro/upload-release-action@v2
    #   with:
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     file: imgpalette.app
    #     asset_name: imgpalette.app
    #     tag: ${{ github.ref }}

    # - name: Build Windows Package
    #   run: fyne package -os windows -icon icon.png

    # - name: Release Windows Package
    #   uses: svenstaro/upload-release-action@v2
    #   with:
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     file: imgpalette.exe
    #     asset_name: imgpalette.exe
    #     tag: ${{ github.ref }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
                Release body
        prerelease: true
        
    - name: List files
      run: ls -alh
    - name: Release with assets
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'imgpalette.{app,tar.gz}'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
